import os
from utils import swift


def dwnload():
    files = ['diplomes_donnees/sas/inputs/dipmana17_ssa.sas7bdat',
             'diplomes_donnees/sas/inputs/dipculture19_ssa.sas7bdat',
             'diplomes_donnees/sas/inputs/dipculture20_ssa.sas7bdat',
             'diplomes_donnees/sas/inputs/dipenq26bis19_ssa.sas7bdat',
             'diplomes_donnees/sas/inputs/dipenq26bis20_ssa.sas7bdat',
             'diplomes_donnees/sas/inputs/dipens15_ssa.sas7bdat', 'diplomes_donnees/sas/inputs/dipens16_ssa.sas7bdat',
             'diplomes_donnees/sas/inputs/dipens17_ssa.sas7bdat', 'diplomes_donnees/sas/inputs/dipens18_ssa.sas7bdat',
             'diplomes_donnees/sas/inputs/dipens19_ssa.sas7bdat', 'diplomes_donnees/sas/inputs/dipens20_ssa.sas7bdat',
             'diplomes_donnees/sas/inputs/dipinge15_ssa.sas7bdat',
             'diplomes_donnees/sas/inputs/dipinge16_ssa.sas7bdat',
             'diplomes_donnees/sas/inputs/dipinge17_ssa.sas7bdat',
             'diplomes_donnees/sas/inputs/dipinge18_ssa.sas7bdat',
             'diplomes_donnees/sas/inputs/dipinge19_ssa.sas7bdat',
             'diplomes_donnees/sas/inputs/dipinge20_ssa.sas7bdat',
             'diplomes_donnees/sas/inputs/dipmana18_ssa.sas7bdat',
             'diplomes_donnees/sas/inputs/dipmana19_ssa.sas7bdat',
             'diplomes_donnees/sas/inputs/dipmana20_ssa.sas7bdat',
             'diplomes_donnees/sas/inputs/dippriv15_ssa.sas7bdat',
             'diplomes_donnees/sas/inputs/dippriv16_ssa.sas7bdat',
             'diplomes_donnees/sas/inputs/dippriv17_ssa.sas7bdat',
             'diplomes_donnees/sas/inputs/dippriv18_ssa.sas7bdat',
             'diplomes_donnees/sas/inputs/dippriv19_ssa.sas7bdat',
             'diplomes_donnees/sas/inputs/dippriv20_ssa.sas7bdat',
             'diplomes_donnees/sas/inputs/result15_ssa.sas7bdat', 'diplomes_donnees/sas/inputs/result16_ssa.sas7bdat',
             'diplomes_donnees/sas/inputs/result17_ssa.sas7bdat', 'diplomes_donnees/sas/inputs/result18_ssa.sas7bdat',
             'diplomes_donnees/sas/inputs/result19_ssa.sas7bdat', 'diplomes_donnees/sas/inputs/result20_ssa.sas7bdat',
             'diplomes_donnees/FORMAT/inscri15/formats.sas7bcat', 'diplomes_donnees/FORMAT/inscri16/formats.sas7bcat',
             'diplomes_donnees/FORMAT/inscri17/formats.sas7bcat', 'diplomes_donnees/FORMAT/inscri18/formats.sas7bcat',
             'diplomes_donnees/FORMAT/inscri19/formats.sas7bcat', 'diplomes_donnees/FORMAT/inscri20/formats.sas7bcat',
             'diplomes_donnees/FORMAT/inscri21/formats.sas7bcat', 'diplomes_donnees/parquet/cometab15.parquet',
             'diplomes_donnees/parquet/cometab16.parquet', 'diplomes_donnees/parquet/cometab17.parquet',
             'diplomes_donnees/parquet/cometab18.parquet', 'diplomes_donnees/parquet/cometab19.parquet',
             'diplomes_donnees/parquet/cometab20.parquet', 'diplomes_donnees/parquet/cometab21.parquet',
             'diplomes_donnees/parquet/dipculture19_ssa.parquet', 'diplomes_donnees/parquet/dipculture20_ssa.parquet',
             'diplomes_donnees/parquet/dipculture21_ssa.parquet',
             'diplomes_donnees/parquet/dipenq26bis19_ssa.parquet', 'diplomes_donnees/parquet/dipinge21_ssa.parquet',
             'diplomes_donnees/parquet/dipenq26bis20_ssa.parquet',
             'diplomes_donnees/parquet/dipenq26bis21_ssa.parquet', 'diplomes_donnees/parquet/dipens15_ssa.parquet',
             'diplomes_donnees/parquet/dipens16_ssa.parquet', 'diplomes_donnees/parquet/dipens17_ssa.parquet',
             'diplomes_donnees/parquet/dipens18_ssa.parquet', 'diplomes_donnees/parquet/dipens19_ssa.parquet',
             'diplomes_donnees/parquet/dipens20_ssa.parquet', 'diplomes_donnees/parquet/dipens21_ssa.parquet',
             'diplomes_donnees/parquet/dipinge15_ssa.parquet', 'diplomes_donnees/parquet/dipinge16_ssa.parquet',
             'diplomes_donnees/parquet/dipinge17_ssa.parquet', 'diplomes_donnees/parquet/dipinge18_ssa.parquet',
             'diplomes_donnees/parquet/dipinge19_ssa.parquet', 'diplomes_donnees/parquet/dipinge20_ssa.parquet',
             'diplomes_donnees/parquet/dipmana17_ssa.parquet', 'diplomes_donnees/parquet/dipmana18_ssa.parquet',
             'diplomes_donnees/parquet/dipmana19_ssa.parquet', 'diplomes_donnees/parquet/dipmana20_ssa.parquet',
             'diplomes_donnees/parquet/dipmana21_ssa.parquet', 'diplomes_donnees/parquet/dippriv15_ssa.parquet',
             'diplomes_donnees/parquet/dippriv16_ssa.parquet', 'diplomes_donnees/parquet/dippriv17_ssa.parquet',
             'diplomes_donnees/parquet/dippriv18_ssa.parquet', 'diplomes_donnees/parquet/dippriv19_ssa.parquet',
             'diplomes_donnees/parquet/dippriv20_ssa.parquet', 'diplomes_donnees/parquet/dippriv21_ssa.parquet',
             'diplomes_donnees/parquet/rattach15.parquet', 'diplomes_donnees/parquet/rattach16.parquet',
             'diplomes_donnees/parquet/rattach17.parquet', 'diplomes_donnees/parquet/rattach18.parquet',
             'diplomes_donnees/parquet/rattach19.parquet', 'diplomes_donnees/parquet/rattach20.parquet',
             'diplomes_donnees/parquet/rattach21.parquet', 'diplomes_donnees/parquet/result15_ssa.parquet',
             'diplomes_donnees/parquet/result16_ssa.parquet', 'diplomes_donnees/parquet/result17_ssa.parquet',
             'diplomes_donnees/parquet/result18_ssa.parquet', 'diplomes_donnees/parquet/result19_ssa.parquet',
             'diplomes_donnees/parquet/result20_ssa.parquet', 'diplomes_donnees/parquet/result21_ssa.parquet']
    for file in files:
        swift.download_object("sas", file, "/data/"+file)
